##### 公共 配置 #######

#内置Tomcat容器配置
server:
  port: 8080
  servlet:
    session:
      timeout: 1800 #session有效时长 单位秒
    context-path: /spadmin #共通访问路径

#基础配置
spring:
  application:
    name: sd

  #修改thymeleaf访问根路径
  thymeleaf:
    prefix: classpath:/views/
